"""init

Revision ID: 5d5afccf287a
Revises: 
Create Date: 2026-03-21 06:36:00.221394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5afccf287a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_problems_contest_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_duels_problem_id'), table_name='duels')
    op.drop_table('duels')
    op.drop_table('rooms')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('room_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('duel_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['duel_id'], ['duels.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('xp', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=1)
    op.create_table('submissions',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('duel_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('room_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('problem_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('language', sa.VARCHAR(length=16), nullable=False),
    sa.Column('code', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('stdout', sa.TEXT(), nullable=True),
    sa.Column('stderr', sa.TEXT(), nullable=True),
    sa.Column('runtime_ms', sa.INTEGER(), nullable=True),
    sa.Column('memory_kb', sa.INTEGER(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['duel_id'], ['duels.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('host_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('title', sa.VARCHAR(length=128), nullable=True),
    sa.Column('problem_id', sa.VARCHAR(length=128), nullable=True),
    sa.Column('max_participants', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('duels',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('initiator_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('opponent_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('problem_id', sa.VARCHAR(length=128), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('winner_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['opponent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_duels_problem_id'), 'duels', ['problem_id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('contest_id', sa.INTEGER(), nullable=True),
    sa.Column('index', sa.VARCHAR(length=10), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('time_limit', sa.INTEGER(), nullable=True),
    sa.Column('memory_limit', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_contest_id'), 'problems', ['contest_id'], unique=False)
    # ### end Alembic commands ###
